fixing

diff --git a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80 b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
--- a/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
+++ b/0x0E-web_stack_debugging_1/0-nginx_likes_port_80
@@ -1,7 +1,10 @@
 #!/usr/bin/env bash
-#a Bash script that configures a server
-nginx_config_file="/etc/nginx/sites-enabled/default"
-sed -i "s/listen 8080 default_server;/listen 80 default_server;/" "$nginx_config_file"
-sed -i "s/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/" "$nginx_config_file"
-sed -i "s/ ipv6only=on//" "$nginx_config_file"
-service nginx restart
+#a Bash script that configuresrver
+if [ -x "$(command -v nginx)" ]; the
+  sed -i -e 's/listen [::]:80 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
+  service nginx restart
+  echo 'Nginx configured to listen on port 80 of all active IPv4 IPs.'
+else
+  echo 'Error: Nginx is not installed.' >&2
+  exit 1
+fi
